### ISSUE TITLE
Synching changes in the .contents.xml file not being reflected in CRX/DE or component

### ISSUE THREAD

**Issue by mabrowncolumbia** [Yinkai15/vscode-aem-sync#2]
I am synching from VS Code to AEM 6.4

I make a change in the .content.xml file for a component and save. 
In the output panel it shows:

> Attempting to sync to AEM
>  
> saving approx 0 nodes... 

And no change is reflected in AEM. 

If I make a change to the html file and save it saves the changes correctly. (very exciting...)

Am I doing this wrong?

**Comment by Yinteger** [comment]
Hey thanks for reporting this issue.  I am able to replicate it with 6.1.  I'll look into fixing it shortly.

**Comment by Yinteger** [comment]
As a temp solution, it looks like it syncs fine if you right click the parent folder of the .content.xml file and click Sync to AEM.  But that will sync the entire node/folder.

**Comment by mabrowncolumbia** [comment]
OK I can try that. 

You've done a good thing here with this. Thank you.

**Comment by Yinteger** [comment]
Hey @mabrowncolumbia , I published a new version of AEM Sync today (0.2.3) which addresses this issue.  If you update the extension, let me know if it fixes it for you.

There is still a minor issue, you can read up on it at:
https://github.com/Yinkai15/vscode-aem-sync/issues/4

But this issue really shouldn't ever come up in normal usage.
