### ISSUE TITLE
AEM-6.2: Port 4502

### ISSUE THREAD

**Issue by rajrayala** [Yinkai15/vscode-aem-sync#7]
AEM version:6.2: 

I mainly use port 4503 for publish instance, but when I switch back to port 4502 and then try to sync, sometimes it doen't work as expected.

Note: Both Publish and Author instance have same updated code.

**Comment by Yinteger** [comment]
You're switching your publisher instance to 4502?  Does it sync to your publisher instance fine on port 4503?  I haven't tested this against publisher instances since I assumed most people would sync to author, and have the replication agents push to publish.

**Comment by rajrayala** [comment]
In my case, I am able to sync to the publisher instance (port 4503) without any issues. But I had issues when trying to sync with author (port 4502).

**Comment by Yinteger** [comment]
Ah I see.  Are you able to provide any logs?  The plugin should be pushing out text to your Output window under the 'aemsync' category.

**Comment by rajrayala** [comment]
Output:

Attempting to sync to AEM
 
/apps/project-name/components
/apps/project-name/components/pages/test
saving approx 0 nodes... 
Attempting to sync to AEM
 
/apps/project-name/components
U /apps/project-name/components/pages/test
saving approx 1 nodes...

**Comment by Yinteger** [comment]
That log looks like it worked?  Can you explain step by step your process, the outcome, and the expected outcome?  Just so we're on the same page.

**Comment by rajrayala** [comment]
Looks like it worked this time.

In general I used to work on publisher instance (4503), but if I switch back to author instance (4502) and make some changes, It will not work.

**Comment by Yinteger** [comment]
Do you think a feature to publish to both at once might be useful/solve your problem?

**Comment by rajrayala** [comment]
That would be awesome, if it's possible.

**Comment by Yinteger** [comment]
I'll look into adding that feature.

How are you changing what instance you're pointing to?  Going to Preferences -> Settings in VSCode, changing the value, then just changing the file again?

**Comment by rajrayala** [comment]
Flow for changing instance port number:

File -> Preferences -> Settings

Inside settings:
Extensions -> AEM-sync configuration -> Port

Repeating the same process for changing port to 4502 / 4503

**Comment by Yinteger** [comment]
Okay, maybe it's not reading the new variable immediately or something.  I'll see if I can reproduce the issue.

**Comment by rajrayala** [comment]
Sure, Thank you
